export default {
  
    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',
  
    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_ERROR: 'LOGOUT_ERROR',
  
    REFRESH_START: 'REFRESH_START',
    REFRESH_SUCCESS: 'REFRESH_SUCCESS',
    REFRESH_ERROR: 'REFRESH_ERROR',
  
    GET_PROFILES_START: 'GET_PROFILES_START',
    GET_PROFILES_SUCCESS: 'GET_PROFILES_SUCCESS',
    GET_PROFILES_ERROR: 'GET_PROFILES_ERROR',
    RESET_PROFILES_STORE:'RESET_PROFILES_STORE',
    
    CREATE_PROFILE_START: 'CREATE_PROFILE_START',
    CREATE_PROFILE_SUCCESS: 'CREATE_PROFILE_SUCCESS',
    CREATE_PROFILE_ERROR: 'CREATE_PROFILE_ERROR',
  
    UPDATE_PROFILE_START: 'UPDATE_PROFILE_START',
    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_ERROR: 'UPDATE_PROFILE_ERROR',
  
    DELETE_PROFILE_START: 'DELETE_PROFILE_START',
    DELETE_PROFILE_SUCCESS: 'DELETE_PROFILE_SUCCESS',
    DELETE_PROFILE_ERROR: 'DELETE_PROFILE_ERROR',
    
  
    CLEAR_TOKEN:"CLEAR_TOKEN",

    ADD_NOTE_START:" ADD_NOTE_START",
    ADD_NOTE_SUCCESS:" ADD_NOTE_SUCCESS",
    ADD_NOTE_ERROR:" ADD_NOTE_ERROR",


    GET_NOTES_START:"GET_NOTES_START",
    GET_NOTES_SUCCESS:"GET_NOTES_SUCCESS",
    GET_NOTES_ERROR:"GET_NOTES_ERROR",

    UPDATE_NOTE_START:"UPDATE_NOTE_START",
    UPDATE_NOTE_SUCCESS:"UPDATE_NOTE_SUCCESS",
    UPDATE_NOTE_ERROR:"UPDATE_NOTE_ERROR",

    DELETE_NOTE_START:"DELETE_NOTE_START",
    DELETE_NOTE_SUCCESS:"DELETE_NOTE_SUCCESS",
    DELETE_NOTE_ERROR:"DELETE_NOTE_ERROR"
  };