export default {
  
    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',
  
    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_ERROR: 'LOGOUT_ERROR',
  
    REFRESH_START: 'REFRESH_START',
    REFRESH_SUCCESS: 'REFRESH_SUCCESS',
    REFRESH_ERROR: 'REFRESH_ERROR',
    
  
    CLEAR_TOKEN:"CLEAR_TOKEN",

    ADD_NOTE_START:" ADD_NOTE_START",
    ADD_NOTE_SUCCESS:" ADD_NOTE_SUCCESS",
    ADD_NOTE_ERROR:" ADD_NOTE_ERROR",


    GET_NOTES_START:"GET_NOTES_START",
    GET_NOTES_SUCCESS:"GET_NOTES_SUCCESS",
    GET_NOTES_ERROR:"GET_NOTES_ERROR",

    UPDATE_NOTE_START:"UPDATE_NOTE_START",
    UPDATE_NOTE_SUCCESS:"UPDATE_NOTE_SUCCESS",
    UPDATE_NOTE_ERROR:"UPDATE_NOTE_ERROR",

    DELETE_NOTE_START:"DELETE_NOTE_START",
    DELETE_NOTE_SUCCESS:"DELETE_NOTE_SUCCESS",
    DELETE_NOTE_ERROR:"DELETE_NOTE_ERROR",

    GET_USERS_START:"GET_USERS_START",
    GET_USERS_SUCCESS:"GET_USERS_SUCCESS",
    GET_USERS_ERROR:"GET_USERS_ERROR",

    CREATE_USER_START:"CREATE_USER_START",
    CREATE_USER_SUCCES:"CREATE_USER_SUCCES",
    CREATE_USER_ERROR:"CREATE_USER_ERROR",

    DELETE_USER_START:"DELETE_USER_START",
    DELETE_USER_SUCCES:"DELETE_USER_SUCCES",
    DELETE_USER_ERROR:"DELETE_USER_ERROR",
  };